# Generated by Django 4.2.7 on 2023-11-09 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socio_profile', '0002_alter_sociouser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_title', models.CharField(max_length=200, null=True, verbose_name='Post Title')),
                ('post_description', models.TextField(blank=True, null=True, verbose_name='Post Details')),
                ('post_image', models.ImageField(blank=True, upload_to='post/')),
                ('post_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='socio_profile.sociouser', verbose_name='Post Author')),
            ],
            options={
                'verbose_name_plural': 'Socio Post Archive',
                'indexes': [models.Index(fields=['id', 'post_author', 'post_title'], name='post_sociop_id_bdd5f5_idx')],
            },
        ),
    ]
