# Generated by Django 4.2.7 on 2023-11-09 13:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socio_profile', '0002_alter_sociouser_email'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociopost',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='media/post/'),
        ),
        migrations.CreateModel(
            name='BridgeOfPostUserLikes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liked_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_post_bridge', to='socio_profile.sociouser', verbose_name='Liked Author')),
                ('liked_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_liked_bridge', to='post.sociopost', verbose_name='Liked Post')),
            ],
            options={
                'verbose_name_plural': 'Socio Post Liked Archive',
            },
        ),
        migrations.AddField(
            model_name='sociopost',
            name='post_likes',
            field=models.ManyToManyField(related_name='liked_post', through='post.BridgeOfPostUserLikes', to='socio_profile.sociouser'),
        ),
        migrations.CreateModel(
            name='SocioPostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=200, null=True, verbose_name='Comment')),
                ('comment_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_comments', to='socio_profile.sociouser', verbose_name='Comment Author')),
                ('parent_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_comments', to='post.sociopost')),
            ],
            options={
                'verbose_name_plural': 'Socio Post Comment Archive',
                'indexes': [models.Index(fields=['id', 'comment_author', 'parent_post'], name='post_sociop_id_2d2de3_idx')],
                'unique_together': {('comment_author', 'parent_post')},
            },
        ),
        migrations.AddIndex(
            model_name='bridgeofpostuserlikes',
            index=models.Index(fields=['id', 'liked_author', 'liked_post'], name='post_bridge_id_eadd80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bridgeofpostuserlikes',
            unique_together={('liked_author', 'liked_post')},
        ),
    ]
