# Generated by Django 4.2.7 on 2023-11-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_profile', '0002_alter_sociouser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociouser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='media/socio/'),
        ),
    ]
