# Generated by Django 4.2.7 on 2023-11-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_profile', '0003_sociouser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociouser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Profile Bio'),
        ),
    ]
