# Generated by Django 4.2.7 on 2023-11-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_profile', '0004_sociouser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociouser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='socio_profile.sociouser'),
        ),
    ]
