# Generated by Django 4.2.7 on 2023-11-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User'},
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('socian', 'Socian'), ('admin', 'Admin')], default='socian', max_length=20, null=True),
        ),
    ]
